### ISSUE TITLE
Missing data preprocessing script?

### ISSUE THREAD

**Issue by virtualramblas** [babaling/DRPreter#1]
Hi,

The readme file mentions to use a Python script to prepare the training data in PyTorch format:
`python preprocess.py`
but no **preprocess.py** file is present in this repo.

**Comment by babaling** [comment]
Thanks for your feedback. I have edited the readme file regarding data preparation.

**Comment by virtualramblas** [comment]
Thanks Jihye. It works. Closing this issue.
